### PR TITLE
OSOE-125: Remove Gulp Extensions and NPM Targets dependencies

### PR DESCRIPTION
**Pull request by 0liver**
OSOE-125

This is just a temporary change, but allowed me to completely remove Gulp Extensions from the OSOCE repository. As a replacement, Node.js Extensions will be added as part of OSOE-84.

### CODE REVIEW

**Review by Piedone — CHANGES_REQUESTED** [review]
While this PR removes GE usage, it doesn't add NE usage (which it shouldn't anyway but in OSOE-84). I don't see the necessity for it apart from the csproj typo fix, since it'll be a confusing exception down the line (as in, this project needs NE integration but it doesn't have GE like the other such projects because we previously removed it).

Also, the PR title doesn't convey the content of the PR.

**Comment by 0liver** [comment]
I had to remove GE submodule from the OSOCE repo entirely to get the automatic builds run properly. I've already added a note to OSOE-84 about the need to add NE here:

image

**Comment by Piedone** [comment]
Why don't you remove the theme from the solution instead, like you did with the other projects?

**Comment by 0liver** [comment]
Because merging the different version of the solution files has turned out to be one of the biggest time killers.

**Review by Piedone — APPROVED** [review]
OK then.

**Pull request merged**
